<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

<!-- 메인지도 예시! -->
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="../../resources/image/수도권.png" usemap="#image-map">

<map name="image-map">
    <area target="_self" alt="네이버 이동" title="네이버 이동" href="http://www.naver.com" coords="493,905,511,916,516,930,545,958,566,963,585,954,619,949,644,950,653,946,687,912,687,898,676,893,669,883,673,872,669,840,659,834,653,827,642,826,627,823,614,827,612,836,607,847,607,859,593,865,547,865,537,872,537,884,525,898,507,896" shape="poly">
</map>

</body>
</html>